name: "DEV: Deploy"
on: pull_request
jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    outputs:
      app-url: ${{steps.create-ra.outputs.app-url}}
    steps:
      - uses: actions/checkout@v2
      - uses: rlespinasse/github-slug-action@v3.x
      - uses: thedoctor0/zip-release@master
        with:
          type: tar
          directory: server
          filename: ../server-${{env.GITHUB_HEAD_REF_SLUG}}.tgz
          path: "."
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - name: Upload source code to Cloud Storage
      - uses: google-github-actions/upload-cloud-storage@main
        id: upload-file
        with:
          path: ./server-${{env.GITHUB_HEAD_REF_SLUG}}.tgz
          destination: pr-server-tars/server-${{env.GITHUB_HEAD_REF_SLUG}}.tgz
      - run: echo "${{steps.upload-file.outputs.uploaded}}"
      - uses: ./.github/actions/deploy-heroku-ra
        id: create-ra
        with:
          pipeline-id: 6f0589a9-927b-4d01-add3-642b8fdb479a
          branch-name: ${{env.GITHUB_HEAD_REF_SLUG}}
          source-code-dir: ./server-${{env.GITHUB_HEAD_REF_SLUG}}.tgz
          heroku-api-key: ${{secrets.HEROKU_API_KEY}}
          heroku-app-name: lab-pwa-real-estate-pr-${{github.event.number}}
          pr-number: ${{github.event.number}}
          source-file: ${{steps.upload-file.outputs.uploaded}}
  vercel-deploy:
    runs-on: ubuntu-latest
    needs: [heroku-deploy]
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-args: --build-env API_URL=${{ needs.heroku-deploy.outputs.app-url }} #Optional
          vercel-token: V8c8P1WTKaIV1YpgZuEjCZLI # Required
          vercel-org-id: HcwgMHjLOtykGfTD6TtM0ChG #Required
          vercel-project-id: prj_ejffl8r3PjAPqXYvxDhLoLDC0NdD #Required
          working-directory: ./client
