name: "DEV: Deploy"
on: pull_request
jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    outputs:
      app-url: ${{steps.create-ra.outputs.heroku-app-name}}
    steps:
      - uses: actions/checkout@v2
      - uses: rlespinasse/github-slug-action@v3.x
      - uses: thedoctor0/zip-release@master
        with:
          type: tar
          directory: server
          filename: ../server-${{env.GITHUB_REF_SLUG}}.tgz
          path: "."
      - run: ls ./
      - uses: ./.github/actions/deploy-heroku-ra
        id: create-ra
        with:
          source-code-dir: ./server-${{env.GITHUB_REF_SLUG}}.tgz
          heroku-api-key: ${{secrets.HEROKU_API_KEY}}
          heroku-app-name: lab-pwa-real-estate-pr-${{github.event.number}}
    # outputs:
    #   heroku-link: ${{ steps.review-app.outputs.heroku-link }}
    # steps:
    #   - name: Slugify variables
    #     uses: rlespinasse/github-slug-action@v3.x
    #   - run: echo "$GITHUB_REF_SLUG"
    #   - run: echo ${{env.GITHUB_REF_SLUG}}
    #   - uses: actions/checkout@v2
    #   - name: Compress server.tgz
    #     uses: thedoctor0/zip-release@master
    #     with:
    #       type: "tar"
    #       directory: "server"
    #       filename: ../server-${{env.GITHUB_REF_SLUG}}.tgz # ../ is required
    #       path: "."
    #   - run: ls ../
    #   - run: ls .
    #   - uses: actions/setup-node@v1
    #   - name: Upload server.tgz
    #     id: upload
    #     run: |
    #       cd ./ci/publish-storage
    #       npm install
    #       echo "LINK=$(node index.js)" >> $GITHUB_ENV
    #   - name: Deploy to Heroku (Review App)
    #     id: review-app
    #     env:
    #       HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_KEY }}
    #       SOURCE_URL: ${{ env.LINK }}
    #     run: |
    #       cd ./ci/publish-heroku
    #       npm install
    #       node index.js
    #       echo "::set-output name=heroku-link::https://lab-pwa-real-estate-pr-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }').herokuapp.com"

  vercel-deploy:
    runs-on: ubuntu-latest
    needs: [heroku-deploy]
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-args: --build-env API_URL=${{ needs.heroku-deploy.outputs.app-url }} #Optional
          vercel-token: V8c8P1WTKaIV1YpgZuEjCZLI # Required
          vercel-org-id: HcwgMHjLOtykGfTD6TtM0ChG #Required
          vercel-project-id: prj_ejffl8r3PjAPqXYvxDhLoLDC0NdD #Required
          working-directory: ./client
